### ISSUE TITLE
Custom WSDL

### ISSUE THREAD

**Issue by kganders** [crunch-accounting/salesforce-api-php-wrapper#3]
How would I go about utilizing my partner WSDL from Salesforce with this? We have some custom fields.

**Comment by ArthurGuy** [comment]
Hi, this library uses the json api so no wsdl is needed.
All you need to know is the field names in your codebase, for example

```
$sfClient->getRecord('Lead', '00WL0000008wVl1MDE', ['name', 'email', 'custom_field_1__c', 'custom_field_2__c']);
```

**Comment by kganders** [comment]
Yeah, was just coming by to close this after opening it. Sorry for the bother.

**Comment by ArthurGuy** [comment]
Not a problem
